GDSC-Daejin/GDSC-WEB-BackEnd

- src/main/java/Gdsc/web/controller/BasicController.java
> Feature work rocoli Pull Request Test

- src/main/java/Gdsc/web/controller/BasicController.java
> Update BasicController.java test

- src/main/java/Gdsc/web/controller/api/OnboardingMemberApiController.java
- src/main/java/Gdsc/web/controller/api/SupportApiController.java
- src/test/resources/application.properties
- ~/app/step1/loglog.log
> doc: test 로그 설정 delete

- build.gradle
gradle에 logback의존성 추가
- gradle에 logback의존성 추가
- 
-
> build : add logback 의존성

- src/main/java/Gdsc/web/controller/api/AdminApiController.java
- src/main/java/Gdsc/web/service/AdminService.java
> feat AdminService 맴버 권한 변경 추가

- src/test/java/Gdsc/web/controller/api/AdminApiControllerTest.java
- setup에 각 권한 멤버를 생성하도록 수정하였습니다.
- 권한별 조회 테스트를 추가하였고 통과까지 확인하였습니다
코드가 지저분한 감이 있는데 이것에 대해서 어떻게 리팩을 해야 할 지 고민해봐야 될 것 같습니다
> feat admin 권한별 조회 Test 추가

- src/main/java/Gdsc/web/entity/Member.java
- src/main/java/Gdsc/web/service/PostService.java
> fix : post upload

- src/main/java/Gdsc/web/controller/api/PostApiController.java
- src/main/java/Gdsc/web/dto/mapping/PostResponseMapping.java
- src/main/java/Gdsc/web/repository/post/JpaPostRepository.java
- src/main/java/Gdsc/web/service/PostService.java
- src/test/java/Gdsc/web/controller/api/PostApiControllerTest.java
- 자신이 쓴 임시 글을 카테고리 별로 조회 합니다. Gabi 요청 API 
> Feature: 임시글 카테고리별 조회 

- src/main/java/Gdsc/web/controller/api/PostApiController.java
> fix : tmp category api mapping name

- src/main/resources/logback-spring.xml
서버 프로필 마다 서버 확인할 수 있도록 확인!
- 이번에 서버 이전 작업이 완료 되면서 개발 서버 및 운영 서버를 나누었기 때문에 서버 웹 훅 또한 나누었습니다. 
> chore : loging back webhook profile 설정

- build.gradle
> test :full text search indexing 테스트

- build.gradle
> chore : external jar 수정

- src/main/java/Gdsc/web/admin/controller/AdminApiController.java
- src/main/java/Gdsc/web/common/config/security/SecurityConfig.java
- src/main/java/Gdsc/web/common/config/security/WebConfig.java
- src/main/java/Gdsc/web/common/handler/AuthorityAdminHandler.java
- src/main/java/Gdsc/web/common/handler/AuthorityNotGuestHandler.java
- src/main/java/Gdsc/web/member/controller/MemberApiController.java
- src/main/java/Gdsc/web/member/entity/Member.java
- src/main/java/Gdsc/web/member/entity/MemberInfo.java
- src/main/java/Gdsc/web/oauth/controller/RefreshController.java
- src/main/java/Gdsc/web/oauth/handler/TokenAccessDeniedHandler.java
- src/main/java/Gdsc/web/oauth/handler/TokenValidateInterceptor.java
- src/main/java/Gdsc/web/oauth/token/AuthToken.java
- src/main/java/Gdsc/web/post/controller/MyPostApiController.java
- src/main/java/Gdsc/web/post/controller/PostApiController.java
- src/main/java/Gdsc/web/post/repository/PostRepository.java
- src/main/java/Gdsc/web/post/service/MyPostService.java
- src/main/java/Gdsc/web/post/service/PostService.java
- src/test/java/Gdsc/web/annotation/WithCustomMockUser.java
- src/test/java/Gdsc/web/annotation/WithMockCustomUserSecurityContextFactory.java
- src/test/java/Gdsc/web/common/MemberEntityFactory.java
- src/test/java/Gdsc/web/config/WithMockUserSecurityContextFactory.java
- src/test/java/Gdsc/web/controller/BasicControllerTest.java
- src/test/java/Gdsc/web/controller/api/AdminApiControllerTest.java
- src/test/java/Gdsc/web/controller/api/CategoryApiControllerTest.java
- src/test/java/Gdsc/web/controller/api/PostApiControllerTest.java
- src/test/java/Gdsc/web/controller/auth/AuthControllerTest.java
- 인터 셉터 설정으로 권한 또는 로그인이 필요한 API 요청 시 403 error 가 반환 되도록 만들었습니다. 또한 권한에 따라서 막아 뒀습니다. 
> Feature: security setting and Interceptor

- src/main/java/Gdsc/web/common/config/swagger/SwaggerConfig.java
- src/main/java/Gdsc/web/oauth/controller/RefreshController.java
- 스웨거에서 API 테스트를 할 수 있도록 JWT 토큰 로그인을 해두었습니다. Authorize 에 "Bearer 토큰받아온것" 값을 넣어 주면 됩니다. 스웨거 문서는 지속적으로 업데이트 하도록 하겠습니다. 
> docs : Swagger 로그인 설정 추가 

- src/main/java/Gdsc/web/oauth/controller/RefreshController.java
- 토큰 컨텍스트 홀더에 등록을 안해서 문제가 있었습니다. 
> chore : 컨텍스트 홀더에 토큰 등록

- src/main/java/Gdsc/web/oauth/handler/OAuth2AuthenticationSuccessHandler.java
- src/main/java/Gdsc/web/oauth/handler/TokenValidateInterceptor.java
> chore : jwt token info set

- src/main/java/Gdsc/web/post/controller/MyPostApiController.java
- src/main/java/Gdsc/web/post/repository/PostRepository.java
- src/main/java/Gdsc/web/post/service/MyPostService.java
- /api/member/v1/myPost/notTemp/{categoryName} done 
> feature : 내 임시저장글 아닌 글 카테고리 별 불러오기

- src/main/java/Gdsc/web/common/service/AwsS3FileUploadService.java
> chore : server error for fix 로깅 설정

- src/main/java/Gdsc/web/oauth/handler/TokenValidateInterceptor.java
- src/main/java/Gdsc/web/post/service/PostService.java
썸네일이 없을 때 썸네일 넣도록 수정하면 null error 수정
> fix : update post error

- src/main/java/Gdsc/web/common/service/AwsS3FileUploadService.java
- src/main/java/Gdsc/web/post/entity/Post.java
- src/main/java/Gdsc/web/post/service/PostService.java
- AWS S3 active profie 별 파일 디렉토리 설정 , 파일 폴더를 S3에 프로필 별로 나누는 설정
> Feature security setting

- src/main/java/Gdsc/web/post/controller/MyPostApiController.java
- src/main/java/Gdsc/web/scrap/controller/ScrapApiController.java
- myPost , scrap API 등의 API 권한을 변경 
> feature : myPost , scrap API GET API 권한 변경

- src/main/java/Gdsc/web/scrap/repository/JpaScrapRepository.java
- src/main/java/Gdsc/web/scrap/service/ScrapService.java
- Scrap Post response DTO 를 타 Post response 와 일치 시키지 않은 점 해결 
> fix : scrap Post Response Dto setting

- src/main/java/Gdsc/web/common/config/corsConfig/CorsConfigNotReal.java
- src/main/java/Gdsc/web/post/controller/MyPostApiController.java
- src/main/java/Gdsc/web/scrap/controller/ScrapApiController.java
- src/main/java/Gdsc/web/scrap/repository/JpaScrapRepository.java
- src/main/java/Gdsc/web/scrap/service/ScrapService.java
> Release :  My Post GET Mapping 주소 변경 

- .github/workflows/gradle1.yml
- src/main/java/Gdsc/web/scrap/service/ScrapService.java
> chore : 문법 java 11 to java 8

- .github/workflows/gradle1.yml
- src/main/java/Gdsc/web/scrap/repository/JpaScrapRepository.java
- src/main/java/Gdsc/web/scrap/service/ScrapService.java
> fix : 문법 java 11 to java 8

- src/main/java/Gdsc/web/post/repository/CustomizePostRepository.java
- src/main/java/Gdsc/web/post/repository/PostRepositoryImpl.java
- src/main/java/Gdsc/web/post/service/PostService.java
- src/main/java/Gdsc/web/scrap/controller/ScrapApiController.java
- src/main/java/Gdsc/web/scrap/dto/ScrapPostList.java
- src/main/java/Gdsc/web/scrap/service/ScrapService.java
- 검색 기능의 DTO 형식 타  API 같이 변경 , Scarp한 PostId LIST API 생성 
> chore : search return dto 변경 , scarp post id List API

- src/main/java/Gdsc/web/member/service/MemberService.java
- src/main/java/Gdsc/web/scrap/controller/ScrapApiController.java
- src/main/java/Gdsc/web/scrap/repository/JpaScrapRepository.java
- src/main/java/Gdsc/web/scrap/service/ScrapService.java
- 카테고리 별 Scrap Post API 작성 
- 이전 Query Param 과 동일  
> Feature : Scrap Post by Category 

- src/main/java/Gdsc/web/member/service/MemberService.java
- Merge Confict 해결 하다가 잘못 머지한 부분 fix 
> fix : java version

- .gitignore
- src/main/java/Gdsc/web/common/service/AwsS3FileUploadService.java
- src/main/java/Gdsc/web/post/controller/PostApiController.java
- src/main/java/Gdsc/web/post/service/PostService.java
- fix : file delete error
- Post 삭제 시 bucket에 있는 image file 삭제 안되던 것 해결 
- upload 시 client에서 보내는 base64 prefix 삭제   
> fix : file delete error

- src/main/java/Gdsc/web/common/service/AwsS3FileUploadService.java
- src/main/java/Gdsc/web/image/controller/ImageUploadController.java
- src/main/java/Gdsc/web/image/dto/ImageDto.java
- src/main/java/Gdsc/web/image/entity/PostInnerImage.java
- src/main/java/Gdsc/web/image/repository/PostInnerImageRepository.java
- src/main/java/Gdsc/web/image/service/ImageUploadService.java
- src/main/java/Gdsc/web/post/controller/PostApiController.java
- src/main/java/Gdsc/web/post/service/PostService.java
> chore : Post save 시 Post Id return 

- src/main/java/Gdsc/web/post/repository/CustomizePostRepository.java
- src/main/java/Gdsc/web/post/repository/PostRepositoryImpl.java
- src/main/java/Gdsc/web/post/service/PostService.java
- src/test/java/Gdsc/web/scrap/controller/ScrapApiControllerTest.java
- search API 에서 LIMIT query 가 안나가서 paging 안되는 오류 해결 
- Pageable Parameter 전달 
> fix : Search API , Paging error

- build.gradle
- src/main/java/Gdsc/web/admin/controller/AdminApiController.java
- src/main/java/Gdsc/web/post/controller/MyPostApiController.java
- src/main/java/Gdsc/web/post/controller/OtherPostApiController.java
- src/main/java/Gdsc/web/post/controller/PostApiController.java
- src/main/java/Gdsc/web/post/dto/PostResponseDto.java
- src/main/java/Gdsc/web/post/mapper/PostMapper.java
- src/main/java/Gdsc/web/post/service/MyPostService.java
- src/main/java/Gdsc/web/post/service/OtherPostService.java
- src/main/java/Gdsc/web/post/service/PostService.java
- src/main/java/Gdsc/web/scrap/controller/ScrapApiController.java
- src/main/java/Gdsc/web/scrap/service/ScrapService.java
- Mapstruct Mapper 를 이용한 Controller 에서 dto <-> Entity 변환
- 서비스 계층에서의 DTO 의존성 제거 
- Hashtag 리턴 타입 변경
> Feature: refactor Mapper 를 이용한 Controller 에서 dto <-> Entity 변환 , HashTag return 변경

- gradle/wrapper/gradle-wrapper.properties
- gradle 버전 오류로 CI/CD 문제 해결 자바 버전 업 문제
> fix : gradle version

- src/main/java/Gdsc/web/post/controller/PostApiController.java
- 포스트 detail controller return dto 변경
> fix : post detail return dto
